title: "Rodya Hates Math"
name: "Rodya"
description: "The world is full of numbers and wonder!"
url: "https://rodya0116.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: true
locale: "en-US"
