title: "Rodya Hates Math"
description: "The world is full of numbers and wonder!"
url: "https://rodya0116.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true
